# Generated by Django 2.2.6 on 2019-10-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netstats', '0002_auto_20191007_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='average',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='stats',
            name='maxi',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='stats',
            name='mini',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='stats',
            name='st',
            field=models.IntegerField(default=3),
        ),
    ]
