# Generated by Django 2.2.6 on 2019-10-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netstats', '0003_auto_20191007_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='average',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='ip_address',
            field=models.CharField(default='localhost', max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='maxi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='mini',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='packets',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='st',
            field=models.CharField(max_length=100),
        ),
    ]
