# Generated by Django 2.2.6 on 2019-10-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netstats', '0004_auto_20191007_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='packets',
            new_name='packet_loss',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='st',
            new_name='packets_received',
        ),
        migrations.AddField(
            model_name='stats',
            name='packets_transmitted',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='stddev',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stats',
            name='ip_address',
            field=models.CharField(max_length=100),
        ),
    ]
