# Generated by Django 2.2.6 on 2019-10-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netstats', '0005_auto_20191011_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='connection_name',
            field=models.CharField(default='localhost to localhost', max_length=100),
            preserve_default=False,
        ),
    ]
