# Generated by Django 2.2.6 on 2019-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netstats', '0008_filepath_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepath',
            name='ip_address',
            field=models.CharField(default='41.139.227.205', max_length=100),
            preserve_default=False,
        ),
    ]
